/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 src/assets/airplane.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Airplane(props: any) {
  const helixSpeed = 6;
  const { nodes, materials } = useGLTF('/models/Airplane.glb');

  const helix: any = useRef();

  useFrame((_state, delta) => {
    helix.current.rotation.x += delta * helixSpeed;
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.PUSHILIN_Plane_Circle000 as any).geometry}
        material={materials.plane}
      />
      <mesh
        ref={helix}
        geometry={(nodes.PUSHILIN_Plane_Helix as any).geometry}
        material={materials.plane}
        position={[1.09, 0.23, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/Airplane.glb');
