/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 /Users/chayatornkukattikoon/boat/tesak/tesaknext/TesakNextApp/public/models/cloud.glb -t 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Mball010: THREE.Mesh;
  };
  materials: {};
};

export default function Cloud(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cloud.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mball010.geometry}
        material={nodes.Mball010.material}
        position={[1.008, -1.089, -3.668]}
        rotation={[-2.165, 0.453, 3.053]}
      />
    </group>
  );
}

useGLTF.preload('/models/cloud.glb');
