/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/earth.gltf 
Author: JasperTobias (https://sketchfab.com/JasperTobias)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-earth-ce0cce9b528b47c7984bf0b2b600d705
Title: LowPoly Earth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'

export function Earth(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.052]} scale={0.5}>
        <mesh geometry={(nodes['URF-Height_watr_0'] as Mesh).geometry} material={materials.watr} />
        <mesh geometry={(nodes['URF-Height_Lampd_0'] as Mesh).geometry} material={materials.Lampd} />
        <mesh geometry={(nodes['URF-Height_Lampd_Ice_0'] as Mesh).geometry} material={materials.Lampd_Ice} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/earth.gltf')
